name = "Billowing Tooth"

[files]
"./channel.py" = ""
"./Hub.py" = ""
"./pyConst.py" = ""
"./SpikePrime.py" = ""
"./TechElement.py" = ""
"./TechElement_EP2.py" = ""

[js_modules.main]
"./ble.js" = "ble"
"./code.js" = "code_editor"
